apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
  labels:
    app: devopsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: devopsapp:$BUILD_NUMBER
        ports:
        - containerPort: 80
  
  
---
apiVersion: v1
kind: Service
metadata:
  name: my-webapp
spec:
  type: LoadBalancer
  selectors:
    matchLables:
      app: my-webapp
  ports:
  - name: http
    port: 80
    targetport: 8089
